### ISSUE TITLE
Prelaunch issues

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#112]
Before Openverse _officially_ launches, there are several remaining cleanup items and optimizations:

## Frontend 

- [x] Web monetization: confirm Creative Commons' payment pointer still works (it does!)
- [x] WordPress/openverse-frontend#421
- [x] WordPress/openverse-frontend#419
- [ ] IFrame fixes
  - [ ]  Include wp footer and header in the iframe
  - [ ] Hide the built-in header + footer in our WordPress theme
- [ ] Test and document Sentry usage
- [ ] Test and document analytics account

## API

- [ ] Failing provider head checks / result count discrepancy ([discussion here](https://wordpress.slack.com/archives/C02012JB00N/p1637076691110500))
- [x] Make category a string instead of an array
  - [ ] WordPress/openverse-api#359
- [x] Deploy latest API

## Catalog / Prod

- [x] Successful data refresh

**Comment by zackkrida** [comment]
Closing, the associated launch is completed. We can make new tickets for any remaining tasks.
