### ISSUE TITLE
Setup sensitive terms list for the blurring project

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#1169]
As part of project #377 and as explained in #911, we need to create manage a list of sensitive terms for the Openverse project. 

## Tasks

- [x] Publish a "Make" post about the creation of the list and its purpose.
- [x] Ping a WordPress GitHub account maintainer to request that they create the
   `WordPress/openverse-sensitive-terms` repository.
- [x] Initialize the repository with a `README.md` and a blank
   `sensitive-terms.txt` file.
- [x] Create a PR which initializes the sensitive terms list by copying all terms
   from two existing lists and removing any duplicates.
- [x] Identify willing reviewers from the `@WordPress/openverse-maintainers` group
   who are comfortable with looking at the list and reviewing the PR, looking
   for terms which should be removed or missing terms which should be added. Add them to the @WordPress/openverse-sensitive-content-reviewers group
- [x] Add the sensitive terms list as a Terraform resource in the infra repo

**Comment by zackkrida** [comment]
WordPress/openverse-sensitive-terms now exists!

**Comment by zackkrida** [comment]
The sensitive terms list has been published, and next a reference to the file needs to be added to Terraform.

**Comment by sarayourfriend** [comment]
@zackkrida The ingestion server just uses a URL for it now, so we'll only need to add a new environment variable pointing to the raw version of the file from GitHub: 

https://github.com//WordPress/openverse/blob/7427bbd4a8178d05a27e6fef07d70905ec7ef16b/ingestion_server/ingestion_server/utils/sensitive_terms.py#L7-L15

I'll update the project thread with this change as well.

**Comment by sarayourfriend** [comment]
This is finished now that https://github.com/WordPress/openverse-infrastructure/pull/522 is merged.
