### ISSUE TITLE
Clean up after the buttons are implemented

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1187]
## Description

After the new button variants and sizes are implemented in the app, we should remove the unused code.

## Items
- [x] Remove the "primary" variants #1188
- [x] Remove the "action-menu" variants #1146
- [x] Remove the "secondary" variants #2114 #2122
- [x] Remove the "medium-old" size (other `-old` sizes have been deleted, but this was the default, so would probably change some snapshots) #2104 
- [x] Add a "transparent-tx" variant replacing "plain" variant #2137
- [x] Replace some "text" buttons with "transparent-gray" #2149
- [x] Update the search button to use "transparent-tx" instead of "plain" variant #2148
- [x] Update the home link to use "transparent-tx" variant #2136
- [x] Remove the "v-button-old" tests #2137

**Comment by obulat** [comment]
I am merging 2104, so I moved the comment about the "left-over" buttons here.

@fcoveram , here is the list of buttons that use the "old" variants.

## `plain` `VButton`s
`plain` `VButton` variant only adds a focus ring, all other styles are added by the component itself
### `VIconButton`
### `VLogoButton`
<img width="78" alt="Screenshot 2023-05-18 at 7 23 53 PM" src="https://github.com/WordPress/openverse/assets/15233243/d829a28f-f808-4712-99f8-87659adc4816">

### "Clear filters" in `VSearchGridFilter`
<img width="328" alt="Screenshot 2023-05-18 at 7 08 49 PM" src="https://github.com/WordPress/openverse/assets/15233243/b3a81fa4-e86e-4290-96ce-d43493ca37da">

###  License explanation button with the question mark

<img width="608" alt="Screenshot 2023-05-18 at 7 10 24 PM" src="https://github.com/WordPress/openverse/assets/15233243/8bcf7e2f-15c5-4aa5-9e49-6e0be7bdedec">

### The external sources buttons inside the external sources popover

<img width="296" alt="Screenshot 2023-05-18 at 7 12 55 PM" src="https://github.com/WordPress/openverse/assets/15233243/94b924b7-fd8c-436c-bc06-8d2f9ce3daeb">
<img width="319" alt="Screenshot 2023-05-18 at 7 12 25 PM" src="https://github.com/WordPress/openverse/assets/15233243/23a8529d-81b8-4fb7-9164-e680b6bcacbd">

## `text` `VButton`s

###  "Clear" button in the Recent searches popover/modal
<img width="602" alt="Screenshot 2023-05-18 at 7 21 01 PM" src="https://github.com/WordPress/openverse/assets/15233243/c491383d-2764-41f7-8231-81d9269b7890">

<img width="504" alt="Screenshot 2023-05-18 at 7 13 53 PM" src="https://github.com/WordPress/openverse/assets/15233243/7e0061bc-5e5a-4220-8f93-d7b70c32efaa">
<img width="305" alt="Screenshot 2023-05-18 at 7 12 43 PM" src="https://github.com/WordPress/openverse/assets/15233243/682defd0-cf20-40a8-9e7a-326164686d1d">

###  "Clear filters" button in the Content settings modal footer

<img width="518" alt="Screenshot 2023-05-18 at 7 30 09 PM" src="https://github.com/WordPress/openverse/assets/15233243/81ca1596-c42d-4a35-88df-142ebf6395e3">

## Other
The "external sources" button that opens the sources popover uses a special variant because it it a white button with dark-charcoal border when resting, and dark-charcoal when hovered.

<img width="525" alt="Screenshot 2023-05-18 at 7 35 13 PM" src="https://github.com/WordPress/openverse/assets/15233243/9c2cbf03-947b-4879-b489-040721ff0c00">
<img width="522" alt="Screenshot 2023-05-18 at 7 35 22 PM" src="https://github.com/WordPress/openverse/assets/15233243/8f2e6735-beb2-4ecf-9535-eeef596c08e1">

**Comment by fcoveram** [comment]
Thanks for the audit @obulat

As a first comment, all UI components you listed in the comment should be buttons. And then, below you can find the context and button variants for each case.

## `Plain VButton`s

### `VIconButton`

It's not fully clear the scope of this button, and since it includes the audio control component and I plan to suggest an overall improvement, I would keep this element as it is.

### `VLogoButton`

Button's size of `48px` is correct. The symbol button has some other style problems that should be addressed in a different ticket.

### "Clear filters" in `VSearchGridFilter`

Button should be `Small + Transparent Gray`

### License explanation button with the question mark

Button should be `24px`. As in [Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=2484-22552&t=QGH3xsNQo75FRJax-4).

### The external sources buttons inside the external sources popover

I plan to suggest an improvement for this and all popover items, so for now the `42px` size is correct.

----

## `text VButton`s

### "Clear" button in the Recent searches popover/modal

Button should be `Small + Transparent Gray`

### "Clear filters" button in the Content settings modal footer

Button should be `Large + Transparent Gray`

----

## Other

### "external sources" button

This component needs more thought, as reported in #460. So for now, I will keep it as it is.

**Comment by zackkrida** [comment]
I believe we're done here, @fcoveram and @obulat! Awesome work.
