### ISSUE TITLE
Tracking Issue: Fixing provider DAGs

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#1630]
## Problem

In WordPress/openverse#1687, we ran an audit of our provider scripts and associated DAGs. This issue serves to track all of the issues that we found during that audit.

## Tasks

- [x] [Update API key for Brooklyn Museum DAG](https://github.com/WordPress/openverse/issues/1638)
- [ ] [Update API key for Walters DAG](https://github.com/WordPress/openverse/issues/1637)
- [x] [Update API key for RawPixel DAG](https://github.com/WordPress/openverse/issues/1636)
- [x] [Update API key for Smithsonian DAG](https://github.com/WordPress/openverse/issues/1640)
- [x] [Update API key for NYPL DAG](https://github.com/WordPress/openverse/issues/1639)
- [x] [Change Wikimedia Commons schedule interval to `@daily`](https://github.com/WordPress/openverse/issues/1643)
- [x] [Handle duplicate keys in the TSV load_data task](https://github.com/WordPress/openverse/issues/1635)
- [x] [Freesound pull_data task fails when getting audio file size](https://github.com/WordPress/openverse/issues/1634)
- [x] [Museum Victoria DAG fails to pull data
](https://github.com/WordPress/openverse/issues/1633)
- [x] [PhyloPic DAG detects no content even when data exists
](https://github.com/WordPress/openverse/issues/1632)
- [x] [Finnish Museum pull_data freezes and times out](https://github.com/WordPress/openverse-catalog/issues/392)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.
