### ISSUE TITLE
Update the SMK (statensmuseum) provider script

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#1673]
The [provider script for SMK](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/providers/provider_api_scripts/staten_museum.py) does some manual building of image urls:

https://github.com/WordPress/openverse-catalog/blob/b07282dc00ab583a6096e6749f923d34767bd7cc/openverse_catalog/dags/providers/provider_api_scripts/staten_museum.py#L158-L160

These image URLs timeout or take a very long time to download, which has prevented us from making SMK live in Openverse.

## Todos

- [ ] Rename script to SMK for clarity (can also refer to them as the National Gallery of Denmark in comments somewhere, also for clarity)
- [ ] Update the 'full' url to something more reasonable, like a 2000px wide thumbnail (since we refer users to the original source for downloading _anyway_, we shouldn't need the 'true' full URL. We might want it if we ever _do_ support full downloads, but this should be a [separate discussion](https://github.com/WordPress/openverse-catalog/discussions/335).
- [ ] Use any new API fields or metadata available to update the script

Here is an example results endpoint: https://api.smk.dk/api/v1/art/?object_number=kms1&lang=en

Note that there's a `image_hq` boolean field to indicate how big an image is, along with an `image_size` field that gives the exact size, which could be factored into this work.
