### ISSUE TITLE
Audio support in Openverse

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#19]
A long awaited feature for Openverse is support for Audio files. We currently have some [limited audio support through meta search](https://search.creativecommons.org/search/audio?q=beep), but would like to expand this to first-class support for audio files. This issue is meant to track progress on Audio across all three repositories; sub-issues within each repo can and _should_ be made. Feel free to edit this post to link them.

## Supporting documents

- Francisco's original [audio mockups](https://www.figma.com/file/uLYzZQERl22CCT7vmnKNOY/Mockup-S6-Audio-integration)
- [Provider API research](https://docs.google.com/spreadsheets/d/1uFj-oVJj64qGOydAtc3-o_suZIN_BL2ONlmBJzpe9-I/edit?usp=sharing) (avalibility, fields, etc.)

### [Frontend](https://github.com/WordPress/openverse-frontend/issues/118)

> Audio work is tracked in https://github.com/WordPress/openverse-frontend/issues/118

- [x] Search results page defaults to an 'all media types' view (see below example:)
<img width="838" alt="CleanShot 2021-05-10 at 20 44 44@2x" src="https://user-images.githubusercontent.com/6351754/117741476-97060480-b1d0-11eb-91d6-ef08c7fc893b.png">

- [x] Audio results no longer shows meta search; instead shows audio results
- [x] WordPress/openverse-frontend#105 Conditional filters in the sidebar when audio results are present: 
	- Genre
	- Duration
	- Format (filetype)
- [x] New frontend components
    - [x] Audio track list view
        - [x] [waveform](https://github.com/WordPress/openverse-frontend/issues/62)
        - [x] play/pause button
        - [x] license icons
        - [x] duration
        - [x] album art
    - [x] Single audio result view
        - [x] 'similar audio' and 'more from the same creator' sections
        - [x] [download buttons](https://github.com/WordPress/openverse-frontend/issues/76)
        - [x] metadata tables

### [API](https://github.com/wordpress/openverse-api)

- [x] [Django models for audio](https://github.com/WordPress/openverse-api/issues/75)
  - [x] [Reuse code from image models](https://github.com/WordPress/openverse-api/issues/73) 
  - [x] [Identify fields to store](https://github.com/WordPress/openverse-api/issues/82)
- [x] [New endpoints for audio](https://github.com/WordPress/openverse-api/issues/74)
  - [x] [Add DRF serializers for audio](https://github.com/WordPress/openverse-api/pull/105)
  - [x] [Add DRF endpoints for audio](https://github.com/WordPress/openverse-api/pull/108)
- [x] [Make the thumbnail server work with audio album art/images](https://github.com/WordPress/openverse-api/issues/76)
- [x] Add audio ingestion to the Ingestion server
  - [x] [Replace hard-coded media type (image) in the ingestion server with the media type based on db model that's being ingested](https://github.com/WordPress/openverse-api/pull/116)
  - [x] [Add Elasticsearch audio models](https://github.com/WordPress/openverse-api/issues/129)
  - [x] Add audio ingestion to the ingestion server (copying the audio from Upstream DB, and creating the Elasticsearch audio models)
  - [x] [Add Audio sample data in .csv format for local testing](https://github.com/WordPress/openverse-api/issues/118)
  - [x] [Update sample data for audio](https://github.com/WordPress/openverse-api/pull/141)

### [Catalog](https://github.com/wordpress/openverse-catalog)

- [x] [New audio DB table](https://github.com/WordPress/openverse-catalog/issues/88)
  - [x] [Add audio db table and Update loader task to save the audio data to the DB](https://github.com/WordPress/openverse-catalog/pull/111)
  - [x] [Update popularity calculations in the materialized view to include audio](https://github.com/WordPress/openverse-catalog/pull/124)
- [x] [New generic model for a catalog entity with ImageStore as a subclass](https://github.com/WordPress/openverse-catalog/issues/82)
  - [x]  [Add catalog entity subclasses for audio](https://github.com/WordPress/openverse-catalog/issues/84)
- [x] New DAGs for each audio provider ([Provider API research](https://docs.google.com/spreadsheets/d/1uFj-oVJj64qGOydAtc3-o_suZIN_BL2ONlmBJzpe9-I/edit?usp=sharing))
  - [x] [Freesound.org](https://github.com/WordPress/openverse-catalog/issues/16)
  - [x] [Jamendo](https://github.com/WordPress/openverse-catalog/issues/51)
  - [x] Wikimedia Commons
