### ISSUE TITLE
[Meta] WordPress Integrations

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#21]
We intend to integrate Openverse directly with WordPress, to provide WordPress users easy access to openly licensed media, starting with Creative Commons licensed images and soon expanding to audio.

Here are a few initial ideas for integrations:

- [ ] Add Openverse as an external media source to the Image block (see Jetpack: https://github.com/Automattic/jetpack/tree/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/extensions/shared/external-media)
	- Would this mean moving the external media functionality from Jetpack to core/gutenberg directly? 
	- Would Pexels remain, or only Openverse initially?
- [ ] A feature plugin that adds license and attribution info as first-class meta fields to items in the media library
    - Is this a good idea?
    - Is this necessary?
- [ ] Match some functionality of an existing plugin https://github.com/lenasterg/ls-wp-ccsearch
