### ISSUE TITLE
ECS Alarms for anomalous behavior

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2344]
| Start      | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | 
| TBD        | TBD          | TBD              |

## Description

To improve the detection of production incidents, we need to create new alarms in AWS. We also need to connect ECS event bridge in order to base alarms off of ECS system events.

## Documents

- [x] #2297 
  - [live document](https://docs.openverse.org/projects/proposals/monitoring/20230606_implementation_plan_ecs_alarms.html)

## Milestone
https://github.com/WordPress/openverse/milestone/15

## Prior Art

We've previously implemented a handful of CloudWatch alarms for RDS and Elasticsearch metrics.
- https://github.com/WordPress/openverse-infrastructure/issues/520
- https://github.com/WordPress/openverse-infrastructure/issues/284
- https://github.com/WordPress/openverse-infrastructure/issues/416
- https://github.com/WordPress/openverse-infrastructure/issues/256
- https://github.com/WordPress/openverse-infrastructure/issues/150

We also use UptimeRobot which is also configured in our private infrastructure repository: https://github.com/WordPress/openverse-infrastructure/issues/116

Finally, a project proposal was written by @sarayourfriend at the start of 2022 to use Prometheus, Grafana, and other non-AWS tools, but was deprioritized and is only half implemented: https://docs.openverse.org/projects/proposals/monitoring/20220307-project_proposal.html

**Comment by zackkrida** [comment]
An implementation plan for this project is under revision:

https://github.com/WordPress/openverse/pull/2343

**Comment by sarayourfriend** [comment]
Most recent activity has been to merge the baseline code work. Remaining alarms are in the todos and will get picked up as folks wrap up existing work.

**Comment by krysal** [comment]
The work for the API alarms was started and two issues were assigned today in the [Community meeting](https://wordpress.slack.com/archives/C02012JB00N/p1692716407394399) in Slack.

**Comment by krysal** [comment]
### Completed

- The total requests count was added for all services (API, thumbnails & Nuxt) to CloudWatch dashboards with its API alarm WordPress/openverse-infrastructure#582
- Added alarms for Nuxt 2xx and 5xx responses WordPress/openverse-infrastructure#606

### In Progress

- https://github.com/WordPress/openverse-infrastructure/pull/581
- https://github.com/WordPress/openverse/pull/2738
- https://github.com/WordPress/openverse-infrastructure/pull/612
- https://github.com/WordPress/openverse/pull/2974
- https://github.com/WordPress/openverse-infrastructure/pull/614
- https://github.com/WordPress/openverse/pull/3001

### To Do

- https://github.com/WordPress/openverse/issues/2502 CC @stacimc 
- https://github.com/WordPress/openverse/issues/2504 CC @obulat 
- https://github.com/WordPress/openverse/issues/2503

**Comment by krysal** [comment]
## Completed 
All the PRs in my previous comment's "In Progress" section, plus:
- https://github.com/WordPress/openverse-infrastructure/pull/615
- https://github.com/WordPress/openverse/pull/3012 (waiting merge, already approved)
- https://github.com/WordPress/openverse-infrastructure/pull/619

## In Progress
- https://github.com/WordPress/openverse/pull/3053

## To Do
- Anomaly alarms for Nuxt response times and their run books. CC @obulat 
- https://github.com/WordPress/openverse/issues/2503

**Comment by krysal** [comment]
### Completed
- https://github.com/WordPress/openverse-infrastructure/pull/627
- https://github.com/WordPress/openverse/pull/3076
- https://github.com/WordPress/openverse/pull/3053

With an extra:

- https://github.com/WordPress/openverse-infrastructure/pull/632

### In Progress
Now we enter the monitoring phase, for determining the best thresholds for each alarm or whether it is of any use or not.

### To Do
Promote alarms to the `#openverse-alerts` channel or retire them after the evaluation period.

**Comment by krysal** [comment]
### In Progress

There were a few missing alarms for anomaly detection, so I made the updates in the following PRs, which are currently in the review phase:
- https://github.com/WordPress/openverse-infrastructure/pull/708
- https://github.com/WordPress/openverse/pull/3420

Also, @stacimc worked on adjusting the thumbnails alarms:
- https://github.com/WordPress/openverse-infrastructure/pull/702

### To Do

- [ ] Reactivate API Response Time alarms

The **Average** and **P99 Response Times for the Production API** are constantly "in alarm" state and therefore, their actions are disabled. It seems that their calculations are off after the normalization they went with the addition of the canary service, because the measurements that the alarms report are different from the CloudWatch dashboard. See the following graphs.

#### API Production Average Response Time

<details>
<summary>Show graphics</summary>

**From the alarm metric**
![From the alarm](https://github.com/WordPress/openverse/assets/9145885/cfbfa76b-a323-4f43-8e7f-0b51e0625755)

**From the ECS-Production-Dashboard**
![From ECS-Production-Dashboard](https://github.com/WordPress/openverse/assets/9145885/fc8c5a0e-bcf9-4de1-bb32-0fe73629f788)

</details> 

#### API Production P99 Response Time

<details>
<summary>Show graphics</summary>

**From the alarm metric**
![From the alarm metric](https://github.com/WordPress/openverse/assets/9145885/09968136-8311-4139-8967-219b491bc9e5)

**From the ECS-Production-Dashboard**
![From the ECS-Production-Dashboard](https://github.com/WordPress/openverse/assets/9145885/edf8292f-43d7-4912-849d-d1847d2c8713)

</details> 

To me, it seems the problem is here:
![Screenshot 2023-11-30 at 17-15-36 Metrics CloudWatch us-east-1](https://github.com/WordPress/openverse/assets/9145885/a19bc12d-d1d7-4a4c-b144-a339669c3da9)
 But I want to confirm with @sarayourfriend the logic behind it.

**Comment by krysal** [comment]
### In Progress
- [ ] https://github.com/WordPress/openverse/pull/3523
- [ ] https://github.com/WordPress/openverse-infrastructure/pull/723
- [ ] https://github.com/WordPress/openverse-infrastructure/pull/724
- [ ] https://github.com/WordPress/openverse-infrastructure/pull/725

### To Do
- [ ] Adjust and stabilize Nuxt alarms

**Comment by krysal** [comment]
With the last round of changes...
- [x] WordPress/openverse-infrastructure#752
- [x] WordPress/openverse-infrastructure#753
- [x] #3652
- [x] #3672

... the project is completed!
