### ISSUE TITLE
Frontend response count alarms

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2505]
## Description

Project thread: https://github.com/WordPress/openverse/issues/2344
Implementation plan: https://docs.openverse.org/projects/proposals/monitoring/20230606_implementation_plan_ecs_alarms.html

Create alarms in `next/modules/monitoring/production-frontend` for the following:

- [x] Request count anomalous for time period: WordPress/openverse-infrastructure#612
- [x] 5xx count over time period over threshold: WordPress/openverse-infrastructure#606
- [x] 2xx count over time period under threshold: WordPress/openverse-infrastructure#606

## Additional context

This issue will remain open until the alarms are stabilised.

~~Blocked by the baseline configuration changes in https://github.com/WordPress/openverse/issues/2499~~

**Comment by obulat** [comment]
Reopening this issue until the alarm is stabilized, based on the description: "_This issue will remain open until the alarms are stabilised._"
