### ISSUE TITLE
[Meta] 3D Models

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#31]
We currently index some Thingiverse and Sketchfab models in Openverse within the 'images' section. We should add a dedicated 3D Models section to the site.

## Initial 'meta search' integration

- [ ] Add a new "3D Models" tab to the site that only has meta search (matching the current audio and video behavior)
    - [ ] Include Sketchfab in 3D meta search
    - [ ] identify other open licensed 3D model search engines (like the deprecated [Google Poly](https://poly.google.com/), which shuts down June 30th 2021

## Full functionality

- [ ] Identify metadata unique to 3D models
- [ ] Identify new 3D model providers
- [ ] Design listing and single result pages for 3D models
	- [ ] Research 3D model viewer libraries. Sketchfab has an easy-to-use sdk (we already use it for their models, see [example](https://search.creativecommons.org/photos/e470f21d-bb02-49c3-8909-ebf27ef20dc2)

**Comment by zackkrida** [comment]
Closing in favor of the merged RFC (#171) and new per-repo milestones.
