### ISSUE TITLE
Update frontend dependencies

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3242]
## Problem

Several frontend dependencies are outdated, and can be updated to a later version.

This is a meta issue. Please open one PR per item in this list:

- [ ] #3247 `nuxt`, `@nuxt/vue-app`, `@nuxt/types`:  from 2.17.0 to `^2.17.2` [changes](https://github.com/nuxt/nuxt/compare/v2.17.0...v2.17.2), [changelog for 2.17.1](https://github.com/nuxt/nuxt/releases/tag/v2.17.1), [changelog for 2.17.2](https://github.com/nuxt/nuxt/releases/tag/v2.17.2),  `vue`, `vue-server-renderer`, `vue-template-compiler`: from 2.7.14 to `^2.7.15`[changelog for 2.7.15](https://github.com/vuejs/vue/releases/tag/v2.7.15)
- [ ] #3248 `@nuxtjs/sentry`: from 7.3.0 to `^7.5.0` [changes](https://github.com/nuxt-community/sentry-module/compare/v7.3.0...v7.5.0), [changelog for 7.5.0](https://github.com/nuxt-community/sentry-module/releases/tag/v7.5.0), [changelog for 7.4.0](https://github.com/nuxt-community/sentry-module/releases/tag/v7.4.0)
- [ ] #3249 `@nuxtjs/i18n`: from 7.0.3 to `^7.3.1`[changes](https://github.com/nuxt-modules/i18n/compare/v7.0.3...v7.3.1)
- [ ] #3250 `@popperjs/core`: from `2.11.2` to `^2.11.8` [changes](https://github.com/floating-ui/floating-ui/compare/v2.11.2...v2.11.8), [2.11.8 changelog](https://github.com/floating-ui/floating-ui/releases/tag/v2.11.8)
- [ ] #3252 `clipboard`: from  2.0.8 to `^2.0.11` [changes](https://github.com/zenorocha/clipboard.js/compare/v2.0.8...v2.0.11)
- [ ] #3253 `tailwindcss`: [^3.3.3](), `@tailwindcss/typography`: [^0.5.10], `autoprefixer`: [^10.4.16](https://github.com/postcss/autoprefixer/releases/tag/10.4.16)
- [ ]  #3254 `vue-demi`: from 0.13.11 to `^0.14.6` [changes](https://github.com/vueuse/vue-demi/compare/v0.13.11...v0.14.6) - 
- [ ] #3255 `uuid`: from 8.3.2 to `^9.0.1` [changes since 8.3.2](https://github.com/uuidjs/uuid/compare/v8.3.2...v9.0.1), `@types/uuid` (^9.0.6)
- [ ] #3256 `focus-trap`: from 7.1.0 to `^7.5.4` [changes](https://github.com/focus-trap/focus-trap/compare/v7.1.0...v7.5.4)

## Description

When updating the dependency, update the version in the `frontend/package.json`, run `just install` to update the lock file, and commit both files.

For first-time contributors: please make sure to create a new branch for your PR, and not add changes to your `main` branch.

## Additional context

Many dependencies cannot be updated because we are still on Nuxt 2.

**Comment by khushi-kothari** [comment]
Check this PR https://github.com/WordPress/openverse/pull/3244 
I have updated all dependencies and also updated lock file

**Comment by khushi-kothari** [comment]
Up for creating smaller PRs for each task! You can assign this to me, Thankyou.
