### ISSUE TITLE
[Meta] Issue templates

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#33]
We need new issue templates, especially with a `- [ ] I am interested in implementing this` checkbox.

Sub-issues:
- [x] WordPress/openverse-api#120
- [x] WordPress/openverse-frontend#83
- [x] WordPress/openverse-catalog#115
