### ISSUE TITLE
Switch to Monorepo

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#384]
| ETA        | Start Date | Project Lead    | Actual Ship Date |
| ---------- | ---------- | --------------- | ---------------- |
| 2023-02-19 | 2022-11-24 | @dhruvkb  | TBD              |

## Description

This project combines three repositories into one:
- [frontend](https://github.com/WordPress/openverse-frontend)
- [API](https://github.com/WordPress/openverse-api)
- [openverse](https://github.com/WordPress/openverse)

**Edit:** The project has been expanded to also include the migration of the [Openverse Catalog](https://github.com/WordPress/openverse-catalog).

## Documents

- [x] [Project Proposal and Implementation Plan](https://github.com/WordPress/openverse/pull/336)
- [Milestone](https://github.com/WordPress/openverse/milestone/3)

## Tasks

- [x] #443 
- [ ] Update references to old processes
- [x] Speed up the CI+CD workflow
- [x] Restore ECS prod deploys (https://github.com/WordPress/openverse/pull/767)
- [x] Update references in the infrastructure repo: https://github.com/WordPress/openverse-infrastructure/pull/383
- [x] Update POT path in GlotPress
- [x] #447
- [x] Add migration notices to separate repo READMEs
  - [x] https://github.com/WordPress/openverse-frontend/pull/2196
  - [x] https://github.com/WordPress/openverse-api/pull/1147
- [x] Archive separate repos
- [x] CODEOWNERS issues (details: https://github.com/WordPress/openverse/pull/450#issuecomment-1440096233) https://github.com/WordPress/openverse/issues/850
- [x] Publish a post to our [Make blog](https://make.wordpress.org/openverse/2023/02/22/openverse-is-now-a-monorepo/)
- [x] https://github.com/WordPress/openverse/issues/760
- [x] Issues with Sentry projects pointing to old repos (cc @krysal)

## Prior Art

- Discussion about switching to monorepo https://github.com/WordPress/openverse/issues/192

Note: the start date is the date when the RFC was opened

**Comment by zackkrida** [comment]
>  Update POT path in GlotPress

I've [reached out](https://wordpress.slack.com/archives/C02QB8GMM/p1676993550417059) to the #meta team in Make WP Slack about this change.

**Comment by AetherUnbound** [comment]
I believe https://github.com/WordPress/openverse/pull/767 should restore our ability to do staging & prod deploys manually!

**Comment by zackkrida** [comment]
I've updated the project description to include the scope change of adding the catalog. I also updated the `Estimated End` to **April 15th**, approximately two weeks after we intend to finish the #385 project.

**Comment by dhruvkb** [comment]
# Update 2023-04-15

## Done

The catalog has been merged into the monorepo, making it a true monorepo. The `main` branch has been renamed to `main_old` and kept for posterity for a limited time. The new `main` branch can be acquired locally via

- `git fetch` and `git reset --hard origin/main`
- `git reset --hard 033ab77` and `git pull`

## Next

- Migrate issues from the catalog to here.
- Archive the catalog with a migration notice (similar to  https://github.com/WordPress/openverse-api/commit/1f7877a05abdd9e97a473be3b94c176662bdbec4).
- Move catalog docs into the truly-comprehensive docs site.
  - Update any broken references to the catalog or its components in the docs.

**Comment by dhruvkb** [comment]
I think we can mark this project as completed as the migration of the docs is an ongoing long-term process.
