### ISSUE TITLE
Dark mode visual bugs

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#4911]
## Description

This is a meta issue to track all dark mode bugs identified in the testing #4783.

- [x] #4829 
- [x] Content report form #5026
    - Textarea text is incorrect color
    - Report button disabled state is incorrect
- Some focus rings are missing/incorrect/using the browser default:
  - [x] Fixed in #4983
    - Source in audio details page
    - Footer items
    - Header items
  - Clear button in search input in Search header
  - ...and more, potentially
- Some focus rings have a white halo in dark mode:
  - [x] #4959 components using `focus-bold-filled` style: image and audio on All content results 
  - [x] Fixed in #4983 Links in body content in all internal pages, Link in filter safe browsing section
  - [x] Fixed in #4983 Links in Attribution box
  - [x] #4939 `VSelectField` (theme switcher, language switcher)
  - ...and more, potentially

- [x] #4910
- In light and dark mode: The search input changes the background color when it should just change the placeholder color.
- Audio playhead is incorrect color

**Comment by obulat** [comment]
While trying to fix the "white halo" around the focus outlines, I found [this article](https://css-tricks.com/copy-the-browsers-native-focus-styles/) about `outline-style: auto`: it's not a bug, but a feature in Chrome.

Of course, since we **do** change the colors of outlines based on the background color, we can override it using `outline-style: solid` or `outline-style:none` (when using the `box-shadow` from Tailwind `ring`).
