### ISSUE TITLE
Collect documentation inside Sphinx

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#777]
## Problem

The following documentation exists outside Sphinx.

- [x] `/automations/README.md` #2330
- [x] `/automations/python/README.md` #2330
- [ ] ~`/frontend/test/locales/README.md`~ (removed)
- [ ] ~`/frontend/test/playwright/README.md`~ (removed)
- [x] `/ingestion_server/README.md` #2330

^ Feel free to expand this list of you spot some random documentation somewhere in the repo.

## Description

It might be nice to collect all the developer docs in one place. Due to the overwhelming majority of our code (including the upcoming catalog merge) is Python, that place is Sphinx.

## Additional context

It can be feasible to leave some `README.md` files lying around the code which either only contain links to the relevant Sphinx pages, or are symlinks to the Markdown files building those pages.

**Comment by tammytdo** [comment]
I'd like to work on this

**Comment by tammytdo** [comment]
The frontend READMEs referenced no longer exist, I believe this issue may already be complete!
